FROM almalinux:9
RUN dnf install nginx -y
RUN rm -f /usr/share/nginx/html/index.html
ADD https://github.com/vot5kor/dockerfiles/blob/main/FROM/dockerfile /usr/share/nginx/html/index.html
RUN chmod +r /usr/share/nginx/html/index.html
ADD sample-3.tar /tmp/
CMD ["nginx", "-g", "daemon off;"]